local Rayfield = loadstring(game:HttpGet('https://raw.githubusercontent.com/shlexware/Rayfield/main/source'))()
local Window = Rayfield:CreateWindow({
	Name = "artemis",
	LoadingTitle = "artemis",
	LoadingSubtitle = "strongest punch simulator",
	ConfigurationSaving = {
	   Enabled = false,
	   FolderName = "ArtemisHub", -- Create a custom folder for your hub/game
	   FileName = "ArtemisSPS"
	},
	Discord = {
	   Enabled = false,
	   Invite = "noinvitelink", -- The Discord invite code, do not include discord.gg/. E.g. discord.gg/ABCD would be ABCD.
	   RememberJoins = true -- Set this to false to make them join the discord every time they load it up
	},
	KeySystem = true, -- Set this to true to use our key system
	KeySettings = {
	   Title = "artemis",
	   Subtitle = "key system",
	   Note = "artemis on top (key link copied btw)",
	   FileName = "artemisKey",
	   SaveKey = true,
	   GrabKeyFromSite = true, -- If this is true, set Key below to the RAW site you would like Rayfield to get the key from
	   Key = "https://pastebin.com/raw/2EFtX1V9"
	}
 }) 
 local MainTab = Window:CreateTab("main", 4483362458)
 local MiscTab = Window:CreateTab("misc", 4483362458)
 --> VALUES <--
 getgenv().autoClick = false
 getgenv().autoOrb = false
 getgenv().autoNextWrld = false
 getgenv().autoPet = false
 --> FUNCTIONS <--
    function autoClick()
		while  getgenv().autoClick == true do
local args = {
    [1] = {
        [1] = "Activate_Punch"
    }
}
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
wait(0.0000001)
	end
end
function autoOrb()
	while getgenv().autoOrb == true do
  local plr = game.Players.LocalPlayer.Character.HumanoidRootPart
  local world_number = game.Players.LocalPlayer.leaderstats.WORLD.value
  print(world_number)
  for i, v in pairs(game:GetService("Workspace").Map.Stages.Boosts[world_number]:GetDescendants()) do
  if v.Name == "0" and v.Parent then
  firetouchinterest(plr, v, 0)
  firetouchinterest(plr, v, 1)
  wait(0.3)
  break;
  
  end
  end
  wait(0.3)
	  end
  end
  function autoPet()
	-- Script generated by SimpleSpy - credits to exx#9394
while getgenv().autoPet == true do
local args = {
    [1] = {
        [1] = "UpgradeCurrentPet"
    }
}

game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
wait(0.00001)
end
  end
  function autoNextWrld()
	while getgenv().autoNextWrld == true do
local args = {
    [1] = {
        [1] = "WarpPlrToOtherMap",
        [2] = "Next"
    }
}
game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))
wait(0.0001)
end
  end
--> MENU <--
local autoclick = MainTab:CreateToggle({
	Name = "auto farm",
	CurrentValue = false,
    Flag = "AC",
	Callback = function(Value)
		getgenv().autoClick = Value
		autoClick()
	end,
 })
 local autoorb = MainTab:CreateToggle({
	Name = "auto orb (doesnt work in some worlds)",
	CurrentValue = false,
    Flag = "AO",
	Callback = function(Value)
		getgenv().autoOrb = Value
		autoOrb()
	end,
 })
 local autoNextWrld = MainTab:CreateToggle({
	Name = "auto next world",
	CurrentValue = false,
    Flag = "ANW",
	Callback = function(Value)
		getgenv().autoNextWrld = Value
		autoNextWrld()
	end,
 })

 local FOV = MiscTab:CreateSlider({
	Name = "FOV",
	Range = {0, 180},
	Increment = 60,
	Suffix = "",
	CurrentValue = 70,
	Flag = "Slider1",
	Callback = function(Value)
		game:GetService'Workspace'.Camera.FieldOfView = Value

	end})
	local WalkSpeed = MiscTab:CreateSlider({
		Name = "Walk Speed",
		Range = {30, 180},
		Increment = 60,
		Suffix = "",
		CurrentValue = 50,
		Flag = "Slider2", 
		Callback = function(Value)
			game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = Value

		end,
	})
 local Button = MiscTab:CreateButton({
	Name = "Anti-AFK",
	Callback = function()
		for i,v in pairs(getconnections(game:GetService("Players").LocalPlayer.Idled)) do
			v:Disable()
			end
	end,
 })